import type { Metadata } from "next";
import "./globals.css";
import { Space_Grotesk, Plus_Jakarta_Sans, JetBrains_Mono } from 'next/font/google';
import AuthProvider from "@/context/AuthProvider";
import { SpeedInsights } from "@vercel/speed-insights/next";
import Providers from "@/context/queryProvider";


const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-heading', // Simplified variable name
});

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-body',
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
});

export const metadata: Metadata = {
  title: "BugTrace - Track your errors",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} ${plusJakarta.variable} ${jetbrainsMono.variable} antialiased overflow-x-hidden bg-[#08070e]`}
      >
        <Providers>
          <AuthProvider>
            {children}
            <SpeedInsights />
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
